### ISSUE TITLE
Getting gpg_module not found

### ISSUE THREAD

**Issue by jfrux** [eschulte/node-gpg#1]
```
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: Symbol gpg_module not found.
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/joshua/Projects/wbx-watchdog/node_modules/gpgme/gpgme.js:1:77)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

Any clues?

**Comment by eschulte** [comment]
My guess is that this is related to #2 . I'm not really using this project any more and don't have time to look into it more closely, but I'm happy to apply patches.
